name: ci

on:
  push:
    branches:
      - '**'        # run on every branch
  pull_request:
    branches: [main]
  workflow_dispatch: {}

permissions:
  contents: read

concurrency:
  group: ci-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: Check for build and type issues
    runs-on: ubuntu-latest

    # Pass Worker URL/token to the Astro build (set these as Actions secrets)
    env:
      PUBLIC_TRACE_RELAY_URL: ${{ secrets.PUBLIC_TRACE_RELAY_URL }}
      PUBLIC_TRACE_RELAY_AUTH: ${{ secrets.PUBLIC_TRACE_RELAY_AUTH }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10
          run_install: false

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: '20'           # LTS widely supported by Astro
          cache: pnpm
          cache-dependency-path: pnpm-lock.yaml

      - name: Install dependencies (no frozen lockfile)
        run: pnpm install --no-frozen-lockfile

      # Type/link checks but don't fail the build on TS/MD issues
      - name: Run Astro check (non-blocking)
        run: pnpm astro check
        continue-on-error: true

      # Ensure site builds (static)
      - name: Run Astro build
        run: pnpm build

