name: Update ping-services.json

on:
  workflow_dispatch:
  schedule:
    - cron: "*/30 * * * *"   # every 30 minutes
  push:
    branches: [ main ]
    paths:
      - tools/ping-services.mjs
      - .github/workflows/ping-services.yml

# needed to commit the refreshed JSON back to main
permissions:
  contents: write

# avoid overlapping runs
concurrency:
  group: ping-services
  cancel-in-progress: true

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false  # we'll push with a token below

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install deps (if any)
        run: |
          if [ -f package.json ]; then
            npm ci
          fi

      - name: Generate ping-services.json
        run: node tools/ping-services.mjs

      - name: Commit & push if changed
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if [[ -n "$(git status --porcelain -- public/ping-services.json)" ]]; then
            git config user.name  "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add public/ping-services.json
            git commit -m "chore: refresh ping-services.json"
            git push "https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git" HEAD:main
          else
            echo "No changes."
          fi
